# Generated by Django 3.0.7 on 2021-08-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
