# Generated by Django 3.0.7 on 2021-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_register_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
