# Generated by Django 3.0.7 on 2021-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210804_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='hobby',
            field=models.CharField(default='', max_length=50),
        ),
    ]
