# Generated by Django 3.0.7 on 2021-08-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_register_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insert_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=55)),
                ('date_of_birth', models.DateField(blank=True, default='')),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
