# Generated by Django 3.0.7 on 2021-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_insert_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert_data',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
    ]
