# Generated by Django 3.0.7 on 2021-08-07 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210807_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert_data',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), help_text='Today Date.', null=True),
        ),
    ]
