# Generated by Django 3.0.7 on 2021-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210807_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert_data',
            name='date_of_birth',
            field=models.CharField(default='', max_length=50),
        ),
    ]
