# Generated by Django 3.0.7 on 2021-08-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20210807_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='register',
            name='model_pic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
