# Generated by Django 3.0.7 on 2021-08-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210811_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='model_pic',
        ),
    ]
