# Generated by Django 3.0.7 on 2021-08-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_register_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
