# Generated by Django 3.0.7 on 2021-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateField(),
        ),
    ]
