# Generated by Django 3.0.7 on 2021-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20210811_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
    ]
