# Generated by Django 3.0.7 on 2021-08-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20210817_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
