# Generated by Django 3.0.7 on 2021-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20210817_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
